#!/usr/bin/env bash

cd /var/www/html;
git add .
git stash
git pull --ff-only
composer update
php artisan migrate
php artisan optimize:clear
RUN chmod +x /usr/local/bin/start-container
sudo chown -R :www-data /var/www/html
sudo chmod -R 775 /var/www/html/storage
RUN chmod -R o+w app
RUN chmod -R o+w storage
RUN chmod -R o+w bootstrap
RUN chown -R www-data:www-data \
        /var/www/html/storage \
        /var/www/html/bootstrap/cache
exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf

#cd /var/vh/holding;
#
#if [ ! -z "$WWWUSER" ]; then
#    usermod -u $WWWUSER sail
#fi
#
#if [ ! -d /.composer ]; then
#    mkdir /.composer
#fi
#
#chmod -R ugo+rw /.composer
#
#if [ $# -gt 0 ]; then
#    exec gosu $WWWUSER "$@"
#else
#    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
#fi
